# Test file to create pipeline

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  

jobs:
  build:
    runs-on: ubuntu-latest
# run the file
    steps:
    # checks out repository under $GITHUB_workspace so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
          python-version 3.8
    - name: Install dependencies
      run: |
         make install
    - name: Lint with pylint
      run: |
         make lint
    - name: Test with pytest
      run: |
         make test     
      
