# Test file to create pipeline

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2     
    - name: Run Make Commands
      run: make hello
